1. Write a Python Program to Add Two Matrices?

In [241]:
import numpy as np
try:
    mat_m = np.random.randint(2,50,(3,4))
    mat_n = np.random.randint(50,99,(3,4))
    result = np.add(mat_m,mat_n)
    print(result)
except ValueError:
    print(f"Shapes {mat_m.shape} and {mat_n.shape} do not match to perform addition operation")

[[110 130 105  78]
 [102  79  58 103]
 [118  62 112 118]]


2. Write a Python Program to Multiply Two Matrices?

In [242]:
result = np.multiply(mat_m,mat_n)
print(result)

[[2856 3825 2450  680]
 [2405 1140  165  846]
 [2392  336 2407 2256]]


3. Write a Python Program to Transpose a Matrix?

In [243]:
result = mat_m.T
print(result)

[[42 37 26]
 [45 19  6]
 [35  3 29]
 [10  9 24]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [244]:
text = "what is square root of two"
words = list(text.split(' '))
words.sort()
print((' ').join(words))

is of root square two what


5. Write a Python Program to Remove Punctuation From a String?

In [245]:
punctuations = ("""!|(|)|-|[|]|{|}|;|:|'|"|\|,|<|>|.|/|?|@|#|$|%|^|&|*|_|~""").split('|')
a = "Are you fool! What are you doing?"
l = []
for i in a:
    if i in punctuations:
        l.append(" ")
    else:
        l.append(i)
        
print(("").join(l))

Are you fool  What are you doing 
